version: '2'

services:

    opac_mongo:
        image: mongo:latest
        restart: always
        user: mongodb
        hostname: opac-mongo
        ports:
          - "27017:27017"

    opac_webapp:
        image: scieloorg/opac
        user: nobody
        restart: always
        hostname: opac_webapp
        depends_on:
            - opac_mongo
        volumes:
            - ./data:/app/data
        links:
            - opac_mongo:opac-mongo
        ports:
            - "8000:8000"
        environment:
            - OPAC_DEBUG_MODE=True
            - OPAC_MONGODB_NAME=opac_mongo
            - OPAC_DATABASE_DIR=/app/data
            - OPAC_SECRET_KEY=s3kr3tk3y
            - OPAC_MONGODB_HOST=opac-mongo
